---
- name: CentOS-Master | Update package cache
  ansible.builtin.yum:
    update_cache: true

- name: CentOS-Master | Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: CentOS-Master | Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: CentOS-Master | Install a list of packages with a list variable
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - yum-utils

- name: CentOS-Master | Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: CentOS-Master | Put SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: CentOS-Master | Check if Docker repository file is present
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_repo_status

- name: CentOS-Master | Add Docker repository if not present
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: docker_repo_status.stat.exists == false

- name: CentOS-Master | Add kubernetes repository
  template:
    src: kubernetes.repo.j2
    dest: "/etc/yum.repos.d/kubernetes.repo"
    owner: root
    group: root
    mode: 0644

- name: CentOS-Master | load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: CentOS-Master | set bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: CentOS-Master | set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: CentOS-Master | create an empty file for Kubernetes sysctl params
  copy:
    content: ""
    dest: /etc/sysctl.d/k8s.conf
    force: no

- name: CentOS-Master | configure sysctl params for Kubernetes
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
  with_items:
    - 'net.bridge.bridge-nf-call-iptables  = 1'
    - 'net.ipv4.ip_forward                 = 1'
    - 'net.bridge.bridge-nf-call-ip6tables = 1'

- name: CentOS-Master | apply sysctl params without reboot
  command: sysctl --system

- name: CentOS-Master | Disable and stop Firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon-reload: yes