---    
- name: Ubuntu-Master | Install kubernetes packages
  ansible.builtin.apt:
    pkg:
    - kubelet={{ kubernetes_major_version }}.*
    - kubeadm={{ kubernetes_major_version }}.*
    - kubectl={{ kubernetes_major_version }}.*
    - containerd.io
    state: present

- name: Ubuntu-Master | Configuring the systemd cgroup driver for Containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '            SystemdCgroup = false'
    line: '            SystemdCgroup = true'

- name: Ubuntu-Master | Updating /etc/containerd/config.toml
  lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    regexp: '^disabled_plugins = \["cri"\]'

- name: Ubuntu-Master | Enable and restart Containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Ubuntu-Master | Enable and restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    enabled: yes

- name: Ubuntu-Master | Initialize the cluster
  shell: kubeadm init --apiserver-advertise-address="{{ master_node-advertise_ip }}" --pod-network-cidr=192.168.0.0/16

- name: Ubuntu-Master | create .kube directory
  become: yes
  become_user: "{{ master_node_username }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Ubuntu-Master | copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ master_node_username }}/.kube/config
    remote_src: yes
    owner: "{{ master_node_username }}"

- name: Ubuntu-Master | install calico Pod network
  become: yes
  become_user: "{{ master_node_username }}"
  shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml
  args:
    chdir: $HOME

- name: Ubuntu-Master | Get join command
  shell: kubeadm token create --print-join-command
  register: my_join_command

- name: Ubuntu-Master | set join command
  set_fact:
    join_command: "{{ my_join_command.stdout_lines[0] }}"r