---    
- name: Ubuntu | Install kubernetes packages
  ansible.builtin.apt:
    pkg:
    - kubelet={{ kubernetes_major_version }}.*
    - kubeadm={{ kubernetes_major_version }}.*
    - kubectl={{ kubernetes_major_version }}.*
    - containerd.io
    state: present

- name: Ubuntu | Configuring the systemd cgroup driver for Containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '            SystemdCgroup = false'
    line: '            SystemdCgroup = true'

- name: Ubuntu | Updating /etc/containerd/config.toml
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'disabled_plugins = ["cri"]'
    line: '#disabled_plugins = ["cri"]'

- name: Ubuntu | Enable and restart Containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Ubuntu | Enable and restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    enabled: yes