---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: (ansible_facts['distribution'] == "CentOS" and ansible_os_family == 'CentOS' and ansible_architecture = 'x86_64')

