---
- name: CentOS-Worker | Update package cache
  ansible.builtin.yum:
    update_cache: true

- name: CentOS-Worker | Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: CentOS-Worker | Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: CentOS-Worker | Install a list of packages with a list variable
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - yum-utils

- name: CentOS-Worker | Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: CentOS-Worker | Put SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: CentOS-Worker | Check if Docker repository file is present
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_repo_status

- name: CentOS-Worker | Add Docker repository if not present
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: docker_repo_status.stat.exists == false

- name: CentOS-Worker | Add kubernetes repository
  template:
    src: kubernetes.repo.j2
    dest: "/etc/yum.repos.d/kubernetes.repo"
    owner: root
    group: root
    mode: 0644

- name: CentOS-Worker | load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: CentOS-Worker | set bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: CentOS-Worker | set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: CentOS-Worker | create an empty file for Kubernetes sysctl params
  copy:
    content: ""
    dest: /etc/sysctl.d/k8s.conf
    force: no

- name: CentOS-Worker | configure sysctl params for Kubernetes
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
  with_items:
    - 'net.bridge.bridge-nf-call-iptables  = 1'
    - 'net.ipv4.ip_forward                 = 1'
    - 'net.bridge.bridge-nf-call-ip6tables = 1'

- name: CentOS-Worker | apply sysctl params without reboot
  command: sysctl --system

- name: CentOS-Worker | Disable and stop Firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon-reload: yes

- name: CentOS-Worker | Update package cache
  ansible.builtin.yum:
    cacheonly: true

- name: CentOS-Worker | Install kubernetes packages
  ansible.builtin.yum:
    pkg:
    - kubelet
    - kubeadm
    - containerd.io
    disable_excludes : kubernetes
    state: present

- name: CentOS-Worker | Configuring the systemd cgroup driver for Containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '            SystemdCgroup = false'
    line: '            SystemdCgroup = true'

- name: CentOS-Worker | Updating /etc/containerd/config.toml
  lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    regexp: '^disabled_plugins = \["cri"\]'

- name: CentOS-Worker | Enable and restart Containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: CentOS-Worker | Enable and restart kubelet service
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: CentOS-Worker | join worker to master
  shell: "{{ hostvars['master_node_advertise_ip'].join_command }}"